### ISSUE TITLE
Comments in FEE should be preserved in FEA

### ISSUE THREAD

**Issue by ctrlcctrlv** [simoncozens/fontFeatures#11]

**Comment by ctrlcctrlv** [comment]
Here's a quick and dirty, very evil patch that takes advantage of the fact that my scripts allow `fee2fea` to dump to stdout then use input redirection:

```
diff --git a/fontFeatures/feeLib/__init__.py b/fontFeatures/feeLib/__init__.py
index 7936b4e..a512c61 100644
--- a/fontFeatures/feeLib/__init__.py
+++ b/fontFeatures/feeLib/__init__.py
@@ -132,7 +132,7 @@ feefile = wsc statement+
 statement = verb:v wsc callRule(v "Args"):args ws ';' wsc -> parser.do(v, args)
 rest_of_line = <('\\\n' | (~'\n' anything))*>
 wsc = (comment | ' ' | '\t' | '\n')+ | ws
-comment = '#' rest_of_line ws?
+comment = '#' rest_of_line:comment ws? -> parser.comment(comment)
 verb = <letter+>:x ?(x in self.valid_verbs) -> x
 
 # Ways of specifying glyphs
@@ -255,5 +255,8 @@ fee_value_record_member = ("xAdvance"| "xPlacement" | "yAdvance" | "yPlacement")
     def do(self, verb, args):
         return self.plugin_classes[verb].action(self, *args)
 
+    def comment(self, comment):
+        print("#{}".format(comment))
+
     def filterResults(self, results):
         return [x for x in collapse(results) if x]
```

I'm sure Simon knows a better way.

**Comment by simoncozens** [comment]
I’m not sure I want to support this properly. We’re only going through FEA because I haven’t bothered to write the binary emitter yet. If FEA wasn’t there there would be no point holding onto comments in the internal representation. And FEE reserves the right to reorder statements to emit the optimal representation of the rules, so the location comments would not be preserved in relation to their original context and might appear in any order. I think it just gets too messy for limited gain.

**Comment by ctrlcctrlv** [comment]
Yes, if you will write a binary emitter, (which would be _absolutely lovely_!! :smiling_face_with_three_hearts::gift_heart::heart_eyes_cat:—thank you,) this makes no sense. Closing as you view FEA as a binary format—which it's honestly ugly enough to be considered one. :hand_over_mouth:

**Comment by alerque** [comment]
Not binary *per se*, but and intermediary compiled format for sure ;-) Transpiling between languages is usually expected to loose any non-semantic information. Very few languages have semantic commenting that can be tracked and maintained after parsing.
