### ISSUE TITLE
`assert(self.markAttachmentSet is not None)` raises an error

### ISSUE THREAD

**Issue by dscorbett** [simoncozens/fontFeatures#51]
```bash
$ curl -LOs https://github.com/googlefonts/noto-fonts/raw/29aa92a9a0768be2d58cf4c590adb5c18b8247c6/unhinted/otf/NotoSansGrantha/NotoSansGrantha-Regular.otf
$ otf2fea NotoSansGrantha-Regular.otf
Traceback (most recent call last):
  File "/usr/local/bin/otf2fea", line 70, in <module>
    print(ff.asFea())
  File "/usr/local/lib/python3.9/site-packages/fontFeatures/feaLib/FontFeatures.py", line 21, in asFea
    return self.asFeaAST(**kwargs).asFea()
  File "/usr/local/lib/python3.9/site-packages/fontFeatures/feaLib/FontFeatures.py", line 149, in asFeaAST
    pre = k.feaPreamble(self)
  File "/usr/local/lib/python3.9/site-packages/fontFeatures/feaLib/Routine.py", line 35, in feaPreamble
    assert(self.markAttachmentSet is not None)
AssertionError
```

**Comment by simoncozens** [comment]
OK. I just came across this myself in a different way (but also trying to turn Noto fonts into feature files... ;-). 

The problem is that when the unparser notices that something has a mark attachment set, it should then go and look in the GDEF table to see what glyphs are involved, and set the `markAttachmentSet` attribute on the routine to those glyphs. It doesn't currently do that; it just sets the flag, but without the glyph set.

(Similarly with the MTI txt2fea thing, we should read the MTI GDEF files before emitting FEA.)

**Comment by simoncozens** [comment]
Actually, no, this is a slightly more specific case - when the unparser is looking at an ExtensionSub or ExtensionPos, needs to read the LookupFlags from the parent lookup, not the extension subtable that we are now pretending is a lookup.
